### PR TITLE
Bug : Some statistics on champions are not accessible

### PR DESCRIPTION
**Pull request by Simire**
Good morning,

I tried to use your library to get some information on base stats champions and I had trouble accessing these informations :+1: 

- 'StatsData' object has no attribute 'criticalStrikeChance'
- 'StatsData' object has no attribute 'attackSpeedOffset'
- 'StatsData' object has no attribute 'attackDamage'

The code I used was like this : 

champions = cass.get_champions()
champions[0].stats.attack_damage
champions[0].stats.critical_strike_chance
champions[0].stats.attack_speed

I didn't try for the per_level of each but I guess the same issue can exist too.

Thanks for your help !

### CODE REVIEW

**Comment by jjmaldonis** [comment]
Hey this should be fixed now. You can update Cass from pip+github using this command to get the latest version:

`pip install -U git+https://github.com/meraki-analytics/cassiopeia.git`

Feel free to re-open this if something isn't working.

**Comment by Simire** [comment]
Hello,

it seems that I still have problems ..

Now, I did what you recommended me and I have these mistakes :

champions[0].stats.magic_resist -> KeyError: <class
'cassiopeia.core.staticdata.champion.StatsData'>
champions = cass.get_champions() -> UnsupportedError: The type "Realms" is
not supported by this DataSource!

Le lun. 14 mai 2018 à 16:10, Jason Maldonis <notifications@github.com> a
écrit :

**Comment by jjmaldonis** [comment]
That's a strange error. Do you have the full error message (it's very long)?

**Comment by Simire** [comment]
Yes, I have it :

champions = cass.get_champions()
Traceback (most recent call last):

  File "<ipython-input-43-cc54dc125162>", line 1, in <module>
    champions = cass.get_champions()

  File
"c:\users\rcolliaux\appdata\local\programs\python\python36-32\lib\site-packages\cassiopeia\cassiopeia.py",
line 96, in get_champions
    return Champions(region=region)

  File
"c:\users\rcolliaux\appdata\local\programs\python\python36-32\lib\site-packages\cassiopeia\core\common.py",
line 213, in __call__
    query["version"] = get_latest_version(region=query["region"],
endpoint=None)

  File
"c:\users\rcolliaux\appdata\local\programs\python\python36-32\lib\site-packages\cassiopeia\core\common.py",
line 64, in get_latest_version
    return Realms(region=region).version

  File
"c:\users\rcolliaux\appdata\local\programs\python\python36-32\lib\site-packages\cassiopeia\core\common.py",
line 214, in __call__
    return pipeline.get(cls, query=query)

  File
"c:\users\rcolliaux\appdata\local\programs\python\python36-32\lib\site-packages\datapipelines\pipelines.py",
line 459, in get
    return handler.get(query, context)

  File
"c:\users\rcolliaux\appdata\local\programs\python\python36-32\lib\site-packages\datapipelines\pipelines.py",
line 185, in get
    result = self._source.get(self._source_type, deepcopy(query), context)

  File
"c:\users\rcolliaux\appdata\local\programs\python\python36-32\lib\site-packages\datapipelines\sources.py",
line 71, in wrapper
    raise DataSource.unsupported(type)

UnsupportedError: The type "Realms" is not supported by this DataSource!

Le mer. 16 mai 2018 à 16:38, Jason Maldonis <notifications@github.com> a
écrit :

**Comment by jjmaldonis** [comment]
Are you using the DiskStore in your settings file? Or a database? Or have you left everything as the defaults?

**Comment by Simire** [comment]
I left everything as the defaults normally !

Le mer. 16 mai 2018 à 16:45, Jason Maldonis <notifications@github.com> a
écrit :

**Comment by Simire** [comment]
Since your first answer, the only thing I did was to install git then use
line of code you told me to use and finally using this code :

@author: rcolliaux
"""
#Librairies

import cassiopeia as cass
from cassiopeia import Champion, Champions
from cassiopeia import Items, Item
from cassiopeia.data import Queue
from cassiopeia.data import Season
from cassiopeia.data import GameMode
from cassiopeia.core import Summoner
import pandas as pd
import numpy as np
import scipy.stats

cass.set_default_region("EUW")
cass.set_riot_api_key("RGAPI-040029ba-3ab4-47df-a75c-8bac6b8e5886")  # This
overrides the value set in your configuration/settings.


#Champion table / Est-ce que l'AS en % il faut pas la séparer parce que ça
peut impacter d'autres calculs? A voir !
champions = cass.get_champions()
champions = Champions(region="EUW")
champions[0].stats

stats = ['armor',
         'magicResistance',
         'attackDamage',
         'attackSpeed',
         'criticalStrikeChance',
         'health',
         'healthRegen',
         'mana',
         'manaRegen',
         'moveSpeed']

Aatrox = pd.DataFrame(index = list(range(18)),columns = stats)

for niveau in range(18):
    Aatrox.at[niveau,'armor'] = champions[0].stats.armor + niveau *
champions[0].stats.armor_per_level
    Aatrox.at[niveau,'magicResistance'] = champions[0].stats.magic_resist +
niveau * champions[0].stats.magic_resist_per_level
    #Aatrox.at[niveau,'attackDamage'] = champions[0].stats.attack_damage +
niveau * champions[0].stats.attack_damage_per_level
    #Aatrox.at[niveau,'attackSpeed'] = champions[0].stats.attack_speed +
niveau * champions[0].stats.percent_attack_speed_per_level
    #Aatrox.at[niveau,'criticalStrikeChance'] =
champions[0].stats.critical_strike_chance + niveau *
champions[0].stats.critical_strike_chance_per_level
    Aatrox.at[niveau,'health'] = champions[0].stats.health + niveau *
champions[0].stats.health_per_level
    Aatrox.at[niveau,'healthRegen'] = champions[0].stats.health_regen #+
niveau * champions[0].stats.health_regen_per_level
    Aatrox.at[niveau,'mana'] = champions[0].stats.mana + niveau *
champions[0].stats.mana_per_level
    Aatrox.at[niveau,'manaRegen'] = champions[0].stats.mana_regen #+ niveau
* champions[0].stats.mana_regen_per_level
    Aatrox.at[niveau,'moveSpeed'] = champions[0].stats.movespeed


Le mer. 16 mai 2018 à 16:47, Rémi Colliaux <remi.colliaux@gmail.com> a
écrit :

**Comment by jjmaldonis** [comment]
Thanks for posting your full code (don't forget to regenerate your API key since it's on github now btw). For some reason I cannot reproduce your error -- I copied and pasted exactly your code, and it runs correctly without erroring.

That means that something happened to your local Cassiopeia files that are causing this, and I don't know what. The easiest thing to do is to uninstall/delete Cassiopeia from your computer entirely, and then install it again.

Try running these commands (I don't know which ones will work):

`pip uninstall cassiopeia`
`pip uninstall git+https://github.com/meraki-analytics/cassiopeia.git`

Then open IPython and try to `import cassiopeia`. If it works, there is still a version of Cass installed on your computer. You can find out where it's located using `cassiopeia.__file__` or `cassiopeia.__package__` or something similar (I can't remember exactly what it is).

Once Cass is fully removed from your computer, try reinstalling it using:

`pip install git+https://github.com/meraki-analytics/cassiopeia.git`

After that, I think everything should work!

**Comment by Simire** [comment]
Thank you very much !

It seems to work perfectly now and I could do what I wanted to do. Thank
you for your work again and have a good day !

Le mer. 16 mai 2018 à 16:58, Jason Maldonis <notifications@github.com> a
écrit :

**Comment by jjmaldonis** [comment]
So `items[0]` is `Boots of Speed` which only has a movespeed. It doesn't have mana regen or ability power or anything, so those numbers should be 0. The actual stats for these items that get returned from the Riot API is sometimes wrong, so we haven't put much time into making sure that Cass gives the correct values because Riot doesn't do it.

That said, to prevent the `AttributeError` from occurring, you can use this line of code instead -- this will return `0` if the stat doesn't exist for that item.

`mana_regen = getattr(my_item, 'mana_regen', 0)`

You should just know that in some cases Riot gives the incorrect data, so don't rely on the data to be perfect.

**Comment by Simire** [comment]
Okay, I didn't know about this but seems clear now and I will take it into
consideration.

Everything is working well and thank you for your time !

Le mar. 22 mai 2018 à 20:22, Jason Maldonis <notifications@github.com> a
écrit :

**Pull request closed without merging**
