### PR TITLE
Fix Summoner.leagues and cassiopeia.get_leagues

### PR DESCRIPTION
**Pull request by sgh304**
This is follow up on #303. Looks like the `leagues` field on summoners is gone now too, meaning this test was failing. I've manually added a `leagues` property to `Summoner` which makes use of the the new `league_entries` API. I also fixed the `get_leagues` function. The test now passes.

### CODE REVIEW

**Comment by jjmaldonis** [comment]
I need to look in the recent issue and PR list to see if we removed Summoner.leagues for a specific reason. If you've seen that convo can you post it here? I'll try to look for it tonight or tomorrow.

**Comment by sgh304** [comment]
Hmm I had kind of just assumed the field had been changed by Riot recently, similar to the `league_positions` -> `league_entries` change. Looks like the PR to support that didn't touch the `Summoner.leagues` field, so possibly this is an older change to the API?

I mostly used the example/test to drive my change -- another option would be to not add `Summoner.leagues` and just remove that functionality from the tests and examples?

**Comment by jjmaldonis** [comment]
Ok so [here's](https://github.com/meraki-analytics/cassiopeia/commit/becf9b0e4703b40d0cf1e279eeb7777c421b7f48#diff-af875a1e7ee7b6f013f6d4df1bb10900) the commit where we removed `Summoner.leagues` entirely. This was part of a huge change that we had to implement when Riot redid their League endpoints around the same time as v4 was released.

[Here's](https://github.com/meraki-analytics/cassiopeia/blob/eaa6cf685ae10885282a75d54522571b6b28b12f/cassiopeia/core/league.py#L343) the old `Summoner.leagues` class implementation. It essentially just provided a nice interface for accessing the three ranked queues: `.fives`, `.flex`, and `.threes` (and now we'd need to add TFT if we add this back).

That `.fives`, etc, functionality has been [implemented](https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/core/league.py#L304) on the `LeagueSummonerEntries` class which is returned by `Summoner.league_entries`, so it'd be redundant to create a new class that has the same methods and have `Summoner.leagues` return it. It also isn't clear to me, from a general perspective as a user thinking about how League of Legends works, what the difference between `Summoner.league_entries` and `Summoner.leagues` would be. Before we had `Summoner.league_positions` and `Summoner.leagues`, which only really made sense if you understood how the Riot API worked. It was a weird interaction, which is why Riot changed it (I'm assuming). I don't think it makes sense to have two `league`-esque methods any more, but feel free to correct me if you can think of a reason why there should be (e.g. maybe there are two types of data that we should be exposing).

So after all that, I think it makes most sense to remove `Summoner.leagues` and instead highlight `Summoner.league_entries.fives` and the other `.flex`, `.threes`, and `.tft` (todo) attributes that exist. If we don't have any working documentation for them right now then that's a big bummer because they are super useful! It saves a for loop and can make your code look a lot cleaner, so it's actually kinda a big deal that we weren't showing that before. Thank you for bring this up because it is an important piece of functionality that everyone should be aware of.

If you'd like to change things to highlight the `Summoner.league_entries.fives` (and similar) methods rather than implementing a `Summoner.leagues` method that'd be awesome. We also definitely need a `.tft` attribute as well since it's ranked, and we should double check that the TFT queues are in the list of ranked queues in the `data.py` file at the top level. If that's stuff you want to tackle that'd be amazing, otherwise I'll try to get to it at some point.

We really appreciate your work here and taking the time to think about this stuff and submitting PRs. It's a huge help! Let me know your thoughts when you get a chance.

**Comment by sgh304** [comment]
Awesome -- thanks so much for all of the explanation, my apologies for not having more understanding of the change in the first place.

I think what you said makes perfect sense, I definitely agree with the decision to keep `Summoner.leagues` removed and instead changing the test/example to remove that usage and in its place highlight the new `Summoner.league_entries.fives` functionality as well as how to pull the league objects from the entries themselves.

I've tweaked my change in this PR to do that. And I just may have to race you to implementing the `.tft` stuff in a followup :).

Thanks again for taking the time to dig everything up.

**Pull request merged**
