### PR TITLE
consistent roles

### PR DESCRIPTION
**Pull request by mertkutay**
until a better role identification code is adapted, this will return correct roles when riot api provides reasonable (role, lane) pairs.

### CODE REVIEW

**Comment by mertkutay** [comment]
also pushed another commit for a typo in runes: dominion -> domination

**Comment by jjmaldonis** [comment]
My hesitation with this is that it opens up an expectation that Cass will fix Riot's role/lane errors. While that would be nice, doing so is a very difficult task.

This is one implementation of trying to fix Riot's role/lane errors, but there are many different ways to do so. For example, we have a [package](https://github.com/meraki-analytics/role-identification) that relies on the champion.gg API that does a pretty good job of return correct roles.

Even if Cass fixed the role/lane errors, it's unlikely we could satisfy a majority of our users with any one implementation. And because of that we've left it up to our users to handle the issue however they see fit.

We're open to being persuaded, but at the moment I don't think we want to introduce any logic to improve Riot's results. If you have use cases and examples and want to try to make your case please do. And we're definitely happy to merge the `str` to `Lane` type fix and the `dominion` typo!

**Comment by mertkutay** [comment]
Thanks for your input. Even though I agree with your hesitation with the false sense of security that will come with cassiopeia's role implementation, I think the library should be consistent. Converting 'DUO_SUPPORT' to cass.Role.support and leaving 'SOLO' as it is makes it confusing. So it should either provide Roles where the (role, lane) pairs are reasonable or it should leave them as they are in every case including 'DUO_SUPPORT' and 'DUO_CARRY'.

My use case with this is, I call the match data from the API, correct role,lane pairs and construct a cass.Match object from the corrected data and expect cass to give correct cass.Role objects. However, that's only my use case.

I can commit additional changes after hearing from you and those typo fixes can be merged.

**Comment by jjmaldonis** [comment]
```
--------------  -------------  ------------  -----
Talon           Lane.top_lane  DUO           False
Yasuo           Lane.jungle                  False
Nunu & Willump  Lane.bot_lane  Role.support  True
Veigar          Lane.mid_lane  SOLO          False
Miss Fortune    Lane.bot_lane  Role.adc      False
Sona            Lane.bot_lane  Role.support  False
Ornn            Lane.jungle                  True
Soraka          Lane.bot_lane  Role.support  False
Kai'Sa          Lane.bot_lane  Role.adc      False
Katarina        Lane.top_lane  DUO           False
Talon           Lane.top_lane  DUO           False
Ahri            Lane.mid_lane  Role.adc      False
Riven           Lane.jungle                  False
Janna           Lane.mid_lane  Role.support  False
Kog'Maw         Lane.bot_lane  SOLO          False
Rengar          Lane.jungle                  True
Nasus           Lane.top_lane  DUO           False
Nidalee         Lane.jungle                  True
Alistar         Lane.bot_lane  Role.support  False
Kalista         Lane.bot_lane  Role.adc      False
Talon           Lane.mid_lane  SOLO          False
Master Yi       Lane.jungle                  True
Brand           Lane.bot_lane  Role.support  False
Teemo           Lane.top_lane  SOLO          False
Kog'Maw         Lane.bot_lane  Role.adc      False
Mordekaiser     Lane.top_lane  SOLO          False
Udyr            Lane.jungle                  True
Lulu            Lane.mid_lane  SOLO          False
Nami            Lane.bot_lane  Role.support  False
Vayne           Lane.bot_lane  Role.adc      False
Talon           Lane.mid_lane  DUO           False
Udyr            Lane.jungle                  True
Vayne           Lane.mid_lane  DUO           False
Morgana         Lane.mid_lane  Role.support  False
Rumble          Lane.top_lane  SOLO          False
Yasuo           Lane.mid_lane  DUO           False
Sona            Lane.bot_lane  Role.support  False
Twitch          Lane.bot_lane  Role.adc      False
Rengar          Lane.jungle                  True
Twisted Fate    Lane.mid_lane  DUO           False
Talon           Lane.mid_lane  SOLO          False
Nasus           Lane.top_lane  SOLO          False
Kha'Zix         Lane.jungle                  True
Veigar          Lane.bot_lane  Role.support  False
Caitlyn         Lane.bot_lane  Role.adc      False
Vayne           Lane.bot_lane  Role.adc      False
Thresh          Lane.bot_lane  Role.support  False
Renekton        Lane.top_lane  SOLO          False
Shaco           Lane.jungle                  True
Fiddlesticks    Lane.mid_lane  SOLO          False
Talon           Lane.mid_lane  SOLO          False
Sivir           Lane.bot_lane  DUO           False
Camille         Lane.jungle                  True
Zyra            Lane.bot_lane  DUO           False
Tryndamere      Lane.top_lane  SOLO          False
Vayne           Lane.bot_lane  Role.adc      False
Ekko            Lane.mid_lane  SOLO          False
Lulu            Lane.bot_lane  Role.support  False
Nasus           Lane.top_lane  SOLO          False
Jax             Lane.jungle                  True
--------------  -------------  ------------  -----
```

**Comment by jjmaldonis** [comment]
```
--------------  -------------  ------------  -----
Talon           Lane.top_lane  DUO           False
Yasuo           Lane.jungle    Role.jungle   False
Nunu & Willump  Lane.bot_lane  Role.support  True
Veigar          Lane.mid_lane  Role.middle   False
Miss Fortune    Lane.bot_lane  Role.adc      False
Sona            Lane.bot_lane  Role.support  False
Ornn            Lane.jungle    Role.jungle   True
Soraka          Lane.bot_lane  Role.support  False
Kai'Sa          Lane.bot_lane  Role.adc      False
Katarina        Lane.top_lane  DUO           False
Talon           Lane.top_lane  DUO           False
Ahri            Lane.mid_lane  DUO_CARRY     False
Riven           Lane.jungle    Role.jungle   False
Janna           Lane.mid_lane  DUO_SUPPORT   False
Kog'Maw         Lane.bot_lane  SOLO          False
Rengar          Lane.jungle    Role.jungle   True
Nasus           Lane.top_lane  DUO           False
Nidalee         Lane.jungle    Role.jungle   True
Alistar         Lane.bot_lane  Role.support  False
Kalista         Lane.bot_lane  Role.adc      False
Talon           Lane.mid_lane  Role.middle   False
Master Yi       Lane.jungle    Role.jungle   True
Brand           Lane.bot_lane  Role.support  False
Teemo           Lane.top_lane  Role.top      False
Kog'Maw         Lane.bot_lane  Role.adc      False
Mordekaiser     Lane.top_lane  Role.top      False
Udyr            Lane.jungle    Role.jungle   True
Lulu            Lane.mid_lane  Role.middle   False
Nami            Lane.bot_lane  Role.support  False
Vayne           Lane.bot_lane  Role.adc      False
Talon           Lane.mid_lane  DUO           False
Udyr            Lane.jungle    Role.jungle   True
Vayne           Lane.mid_lane  DUO           False
Morgana         Lane.mid_lane  DUO_SUPPORT   False
Rumble          Lane.top_lane  Role.top      False
Yasuo           Lane.mid_lane  DUO           False
Sona            Lane.bot_lane  Role.support  False
Twitch          Lane.bot_lane  Role.adc      False
Rengar          Lane.jungle    Role.jungle   True
Twisted Fate    Lane.mid_lane  DUO           False
Talon           Lane.mid_lane  Role.middle   False
Nasus           Lane.top_lane  Role.top      False
Kha'Zix         Lane.jungle    Role.jungle   True
Veigar          Lane.bot_lane  Role.support  False
Caitlyn         Lane.bot_lane  Role.adc      False
Vayne           Lane.bot_lane  Role.adc      False
Thresh          Lane.bot_lane  Role.support  False
Renekton        Lane.top_lane  Role.top      False
Shaco           Lane.jungle    Role.jungle   True
Fiddlesticks    Lane.mid_lane  Role.middle   False
Talon           Lane.mid_lane  Role.middle   False
Sivir           Lane.bot_lane  DUO           False
Camille         Lane.jungle    Role.jungle   True
Zyra            Lane.bot_lane  DUO           False
Tryndamere      Lane.top_lane  Role.top      False
Vayne           Lane.bot_lane  Role.adc      False
Ekko            Lane.mid_lane  Role.middle   False
Lulu            Lane.bot_lane  Role.support  False
Nasus           Lane.top_lane  Role.top      False
Jax             Lane.jungle    Role.jungle   True
--------------  -------------  ------------  -----
```

**Comment by jjmaldonis** [comment]
I just made two comments with before/after changes for your code. They show ~ 50 results of role/lane assignments and whether or not the summoner had smite (True/False). I made them as separate comments so you can open the page in two tabs and easily switch between them for comparison. It looks like one of the main improvements is in the Jungle role assignment (while it still isn't especially accurate, it is more consistent).

Your point that "I think the library should be consistent. Converting 'DUO_SUPPORT' to cass.Role.support and leaving 'SOLO' as it is makes it confusing." is a good one. It would be nice to always return a `Role` enum and never a string. That said, these changes don't fix that issue (although they do help quite a bit). In order to always return a `Role`, we'd need to add more logic to identify the role. At that point we're getting further and further away from Riot's role/lane values, and our users will not be able to access Riot's results (but instead only be able to access Cass's "corrected" results).

How do you handle the issue of not always getting a `Role` in your own code, after you've made your fixes? For example, the top row of the correct results is: `Talon Lane.top_lane DUO False`. What do you do about the `DUO` in this case?

**Comment by mertkutay** [comment]
Thanks for taking the time for preparing these lists. Entry of Ahri shows the need of a change in cass role enums as it has assigned Role.adc to Ahri in mid lane. But I agree with you about losing Riot's original values. It seems we have a few choices here:
1. Extend my code to DUO and DUO_CARRY roles in non-BOTTOM lanes and assign them Role.middle or Role.top according to their lanes. If a DUO_SUPPORT is encountered, they are Role.support no matter what.
2. Ditch custom enums completely and return Role.solo Role.duo etc.
3. Go with choice 1 but add another property for accessing riot's original data

I'd choose the third. What do you think?

**Comment by mertkutay** [comment]
I've push another commit for additional logic in choice 1

**Comment by jjmaldonis** [comment]
A 4th option is to always return `.role` as Riot's string and return `.lane` as Cass's enum. It looks like the Lane enum works well. We'd then have other functionality (probably externally) to return the corrected role. If we do this, Cass would never use the `Role` enum.

My hesitations with options 1-4 are below:

1. There are still going to be niche cases we don't catch, so Cass will still occasionally return a string. We're left with the same issue of returning both strings and enums, with the addition of more logic that isn't obvious to the user and will often still return incorrect results.

2. The idea of `Role.solo` and `Role.duo` make very little intuitive sense, and aren't good abstractions for what people mean when they say "role". "Role" often is used for top/jungle/mid/adc/support, but can also mean tank/support/bruiser/etc. In this case we want it to mean top/jungle/mid/adc/support, so making a `solo` and `duo` abstraction doesn't help our users. I think we both agree this isn't the way to go.

3. We still have the issues in (1), but the additional logic is slightly less of a concern because users still have access to Riot's original data, so it's clear to the user that they can either access Riot's role/lane data or use something else that is presumably better. However, now we're back to the issue in my first comment where users are expecting Cass to give them correct role/lane data.

4. Having `.lane` return an enum and `.role` return a string feels out of sync. We also put the responsibility on the user to figure out how Riot sets the role field, and Cass often tries to fix weird things that Riot does so that feels out of sync as well. Still, I don't think it's reasonable to have Cass always return correct values for the role (partly because there are so many ways to attempt that). With that in mind, I like having any code that tries to fix the role data be external to Cass (e.g. a plugin). So I think we're left with the issues that 1) `.lane` and `.role` return different data types, and 2) Cass does nothing to fix Riot's role data. The benefits are that `.role` always returns the same type, and we can consolidate "fixing Riot's role data" to an external package.

**Comment by mertkutay** [comment]
Seems like the only option that we both can agree on is to always return role property as the original string and leave role correction to an external plugin. If that is OK with you, I can push a final commit.

**Comment by jjmaldonis** [comment]
After talking with Rob about this for a while and thinking about your comments, we've come up with a plan that we think is a decent compromise, is consistent, and is extendable in the future.

We agree with your (2) and think it's best to convert Cass's Role enum to use Riot's values. So the new Role enum will look like this:

```
class Role(Enum):
    duo = "DUO"
    duo_carry = "DUO_CARRY"
    duo_support = "DUO_SUPPORT"
    none = "NONE"
    solo = "SOLO"
```

Second, `Match.role` will return this new enum. Now both `.lane` and `.role` return enums and are consistent with the Riot API values.

Third, if you are interested, we'd like to make your code into a plugin for Cass. Your plugin will do two important things: 1) It will replace the above `Role` enum with the top/jungle/mid/adc/support enum that is currently in Cass, and 2) it will override the `.role` attribute. With your plugin, `.role` will return better values for roles. I'll leave it up to you how you want to handle unidentified role assignments. Is this something you're interested in?

**Comment by mertkutay** [comment]
I've made necessary changes, fixed RunePath image_url bug and added RunePath id's the same way as the image_urls.
As for the plugin, I do not exactly know how to write a cassiopeia plugin from scratch and integrate to the library but I'd be interested in writing the necessary logic with your guidance.

**Comment by jjmaldonis** [comment]
Awesome, thanks! Writing the plugin is kinda fun actually. You're basically just monkey patching a python library (Cass in this case).

Here's an example: https://github.com/meraki-analytics/cassiopeia-plugins/blob/master/cassiopeia-championgg/cassiopeia_championgg/__init__.py

Your package might look something like this:


```python
from merakicommons.cache import lazy_property
import cassiopeia

class Role(Enum):
    top = "TOP"
    jungle = "JUNGLE"
    middle = "MIDDLE"
    adc = "ADC"
    support = "SUPPORT"


# Monkey patch in the Role enum, replacing Cass's other Role enum
cassiopeia.data.Role = Role

# Define and monkey patch in the new role method
def role(self, ...) -> Role:
    # Your logic
role = lazy_property(role)

cassiopeia.core.match.Participant.role = role
```

Your code, or at least the monkey patch part of it, will go in your package's `__init__.py` file. That way, as soon as your package is loaded, it modifies Cass. Then, in order to get it integrated as a plugin in Cass, uses will modify their Cass config file to contain something like this:

```json
"plugins": [
    {
        "package": "mertkutay_role_id"
    }
]
```

where "mertkutay_role_id" is the name of your package. Cass will then import that package during init.

It looks like we need to add some logic to https://github.com/meraki-analytics/cassiopeia/blob/master/cassiopeia/_configuration/settings.py to handle importing the plugins, but it should be pretty simple. I can try to get to that soon.

**Pull request merged**
