### PR TITLE
Implemented Redis Cache

### PR DESCRIPTION
**Pull request by fculpo**
Redis cache is now possible !

Example code to set it up in your app: 
```
from cassiopeia.type.api.store import RedisCache

redis_handle = RedisCache(host='redis', port=6379, db=0, compress=False)
riotapi.set_data_store(redis_handle)
```

### CODE REVIEW

**Comment by jjmaldonis** [comment]
This is cool!  A couple quick questions before I merge:

1) The user will have to manually specify that they want to use redis, right? It won't be used by default? (This is true as far as I can tell but I want to double check.)

2) Have you tested it much? I haven't, so I'm completely relying on you for this. How much have you used it, how many different use cases have you used it with, etc? I'm not asking you to go do more tests, I'd just like to know where you're at. How confident do you feel that other people can use this without running into issues/errors within a day or two of using it?

3) We're going to implement a redis cache in the next update too, do you think we can use some of your code for that?

4) I think we're going to make a Contributors file in the next version with people who have contributed. Would you like to go in it if we do?

Thanks!

**Comment by fculpo** [comment]
Hi,

1. It is not enabled by default, similar setup as SQLAlchemy store
2. It is in "production" in my project and no errors so far, caching works fine. Some more tests could be ran against get_all and has_all methods, and the iterate method is not implemented as i could not find any use in the framework.
3. Sure ! Happy to help :)
4. That would be nice !

Some context on my use and why i decided to switch to redis:
* My app is a Flask served by uwsgi for multiprocessing
* That was initially causing me headaches with SQLAlchemy, because of the threading and multiprocess considerations (transactions would failed and leave a thread in unusable state, etc...)
* API is returning JSON, converted in Python objects, that implement back a to_json method, so it was natural for me to store it in a Redis store instead of a SQL one.
* I would say that my app runs faster now (which should be normal as cache is now in memory, but also persistent across restarts or scaling)

**Comment by jjmaldonis** [comment]
Ok sounds good! I'll merge then.  Follow up question: Were the issues you were having with threading/multiprocessing things that were implemented in Cass, or are they in SQLAlchemy? If it's in Cass, we will need to be more careful next time about how we do that.

**Comment by fculpo** [comment]
well i'm no expert in those things, but i think it is both related to : 
* the instantiation of the database by Cass
* the thread-safety of sqlalchemy (going from 2 to single thread per process helped a bit but there was still some 

Again, it is absolutely possible that some uwsgi trick would have solved it all, but anyway, i wanted the efficiency and rapidity of a redis cache, so here it is :)

**Pull request merged**
